[mypy]
python_version = 3.11
check_untyped_defs = true
warn_unused_ignores = true
cache_dir = .mypy_cache

[mypy-img2pdf.*]
ignore_missing_imports = true

[mypy-natsort.*]
ignore_missing_imports = true

[mypy-pdf2image.*]
ignore_missing_imports = true
